version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_UPLOADS_URL=${VITE_UPLOADS_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
      - REACT_APP_DB_USER=${REACT_APP_DB_USER}
      - REACT_APP_DB_PASS=${REACT_APP_DB_PASS}
      - REACT_APP_JWT_SECRET=${REACT_APP_JWT_SECRET}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: